### ISSUE TITLE
Cannot connect to already running IDE instance. Exception: Process 2 is still running

### ISSUE THREAD

**Issue by Eonfge** [flathub/com.jetbrains.IntelliJ-IDEA-Community#149] opened 2023-09-22 12:09 UTC
### Error
```
Start Failed
Cannot connect to already running IDE instance.
Exception: Process 2 is still running
```

I double-checked, and I can confirm that the flatpak is not already running.

### System

```
System:
  Host: fedora Kernel: 6.4.15-200.fc38.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 44.5 Distro: Fedora release 38 (Thirty Eight)
Machine:
  Type: Laptop System: Notebook product: NH55RGQ v: N/A
    serial: <superuser required>
  Mobo: Notebook model: NH55RGQ serial: <superuser required> UEFI: INSYDE
    v: 1.07.01 date: 05/29/2019
Battery:
  ID-1: BAT0 charge: 44.1 Wh (100.0%) condition: 44.1/48.0 Wh (91.9%)
CPU:
  Info: 6-core model: Intel Core i7-9750H bits: 64 type: MT MCP cache:
    L2: 1.5 MiB
  Speed (MHz): avg: 2758 min/max: 800/4500 cores: 1: 2600 2: 2600 3: 4501
    4: 2600 5: 2600 6: 2600 7: 2600 8: 2600 9: 2600 10: 2600 11: 2600 12: 2600
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX250] driver: nouveau v: kernel
  Device-3: Chicony USB2.0 Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: dri: iris gpu: i915 resolution:
    1: 2560x1440~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 23.1.7 renderer: Mesa Intel UHD Graphics 630 (CFL
    GT2)
Audio:
  Device-1: Intel Cannon Lake PCH cAVS driver: snd_hda_intel
  API: ALSA v: k6.4.15-200.fc38.x86_64 status: kernel-api
  Server-1: PipeWire v: 0.3.80 status: active
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi
  IF: wlp7s0 state: up mac: 50:e0:85:f4:bb:b3
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp8s0f1 state: down mac: 80:fa:5b:6d:51:6b
Bluetooth:
  Device-1: Intel AX200 Bluetooth driver: btusb type: USB
  Report: btmgmt ID: hci0 state: up address: 50:E0:85:F4:BB:B7 bt-v: 5.2
Drives:
  Local Storage: total: 1.36 TiB used: 1.36 TiB (99.9%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 500GB
    size: 465.76 GiB
  ID-2: /dev/sda vendor: Seagate model: ST1000LM048-2E7172 size: 931.51 GiB
Partition:
  ID-1: / size: 464.16 GiB used: 113.16 GiB (24.4%) fs: btrfs dev: /dev/dm-0
  ID-2: /boot size: 973.4 MiB used: 297.2 MiB (30.5%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 598.8 MiB used: 17.4 MiB (2.9%) fs: vfat
    dev: /dev/nvme0n1p1
  ID-4: /home size: 464.16 GiB used: 113.16 GiB (24.4%) fs: btrfs
    dev: /dev/dm-0
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 66.0 C pch: 76.0 C mobo: N/A gpu: nouveau
    temp: 47.0 C
  Fan Speeds (rpm): N/A
Info:
  Processes: 481 Uptime: 35m Memory: total: 32 GiB note: est.
  available: 31.05 GiB used: 7.06 GiB (22.8%) Shell: Bash inxi: 3.3.29
```

It used to work, until I updated my machine so perhaps it's related to one of these updated packages:

```
[kevin@fedora ~]$ dnf history info 331
Transaction ID : 331
Begin time     : Fri 22 Sep 2023 13:30:48 CEST
Begin rpmdb    : a5ea45a03a57e3ffd4c424f2bd8b3849491655bca4c6bcae28336d26d38d72de
End time       : Fri 22 Sep 2023 13:30:57 CEST (9 seconds)
End rpmdb      : fb516b43ce0d99126ed0dd0dc290367e1a47a40dca376ca98c879ed3184572ad
User           : root <root>
Return-Code    : Success
Releasever     : 
Command Line   : 
Comment        : 
Packages Altered:
    Upgrade  container-selinux-2:2.222.0-1.fc38.noarch @updates
    Upgrade  gstreamer1-1.22.6-1.fc38.x86_64           @updates
    Upgrade  python3-gstreamer1-1.22.6-1.fc38.x86_64   @updates
    Upgrade  traceroute-3:2.1.3-1.fc38.x86_64          @updates
    Upgrade  zip-3.0-37.fc38.x86_64                    @updates
    Upgraded container-selinux-2:2.221.1-1.fc38.noarch @@System
    Upgraded gstreamer1-1.22.5-1.fc38.x86_64           @@System
    Upgraded python3-gstreamer1-1.22.5-1.fc38.x86_64   @@System
    Upgraded traceroute-3:2.1.2-1.fc38.x86_64          @@System
    Upgraded zip-3.0-36.fc38.x86_64                    @@System
```

### Screenshot

![Screenshot from 2023-09-22 14-04-14](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/assets/33983090/6389dfba-0684-473f-badd-b57b6784ddc5)

**Comment by Eonfge** [comment] 2023-09-22 12:22
### Triage
Delete `~/.var/app/com.jetbrains.IntelliJ-IDEA-Community` and restart the entire IDE. Not sure what corrupt settings could have led to this problem

**Comment by Makrennel** [comment] 2023-09-22 12:39
I've also had this issue, and I had to rollback to [commit 2d996332](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/commit/2d996332728555900222e3646ac884ef6904fd04) to fix it. It still happens the first time I run intellij after booting, but the second time I run it it launches. On the newer version it just refuses to start no matter how many times I run it.

**Comment by x80486** [comment] 2023-11-25 03:15
Will close this one because it's not a `Flatpak` issue. It was fixed recently.

If it happens again, feel free to open a new issue.

**Closed by x80486** 2023-11-25 03:15 UTC

**Comment by StrangeNoises** [comment] 2023-11-27 17:13
if this was fixed recently can you link to the fix in whatever project this fix was in? :-) Because I hit this today with everything up to date...

in my case this error happens on the second (and subsequent) attempt to launch after the first appeared to fail. the *first* attempt to launch was just hanging (and gnome-shell shows it as a background task that it can't quit). but no java process is running so i reckoned it was hanging somewhere in the launch process before java itself starts up. ie: in the flatpak launch or idea's own launch script.

But I fixed it for me, kinda. And now for some platform specifics: Fedora 39 aarch64 running in vmware fusion player on an apple silicon mac. With NAT neworking it failed as described above. With Bridged networking it works. Launch is slow but it gets there, and thereafter it seems OK. It remains a problem because I need NAT networking to work from the café ;-)

The tarball install of idea didn't have this problem. (But had others, leading me to try flatpak again.) there's no snap version for aarch64...

Is it possible the flatpak launcher doesn't like a double-NAT networking situation? other networking (browsing, ssh to my git repo etc.) was fine.

**Comment by x80486** [comment] 2023-11-27 17:57
Unless this is something new, removing the `.lock` file located at `${HOME}/.var/app/${FLATPAK_ID}/config/JetBrains/${PRODUCT_VERSION}/` should do it.

If it's the same issue, it's definitely not related with `Flatpak`; I've seen it in `Windows` as well — but not recently. I haven't experienced this for some time now.

**Comment by StrangeNoises** [comment] 2023-11-27 18:11
removing the lock file didn't help. (The prompt to do so showed up if you tried launching from the commandline, so it was one of the first things i tried ;-))

**Comment by x80486** [comment] 2023-11-27 18:20
Double check if you have **_the exact same error message_**. If that's the case, make sure no other `IntelliJ IDEA` process is also running, and the `.lock` file is gone.

If this doesn't solve the problem, try to report it here: https://youtrack.jetbrains.com/issue/IDEA-330531

If you think it's a `Flatpak` issue only, provide some steps to reproduce the issue. I'll try to see what might be causing it.

> The `idea.log` file might have something useful.

**Comment by StrangeNoises** [comment] 2023-11-27 18:55
never mind, i can't reproduce it now. more specifically, i started it from the commandline and just *waited*, and it eventually started. the problem basically is that it took several minutes with no visible feedback except gnome-shell saying there was a background process, before the splash screen appears. Subsequent attempts (after quitting) took less time but still over two minutes. Under bridged networking it's slow to start but not that slow, so it feels networky.

i'll leave it for now. if anything there might be a new issue later if I can distill it a bit better. i can't even reproduce the same error per this issue now, which i'm pretty sure i was getting before, but the flatpak has been uninstalled and reinstalled completely since then.
